### ISSUE TITLE
Catalina (10.15.7) users may experience a x509 certificate signed by unknown authority when hitting api.equinix.com/metal/v1 via the provider

### ISSUE THREAD

**Issue by claudiobartolini** [equinix/terraform-metal-multiarch-k8s#82]
I found a workaround for it that worked for me here
-> https://github.com/hashicorp/terraform/issues/22193#issuecomment-610877715
The certificate whose trust I needed to set to "Use system defaults" was issued by Digicert Global Root CA and it was in fact set to "Always Trust". I needed to set it to "Use system defaults" to make it work.

**Comment by displague** [comment]
Thanks for reporting this. I've had to recommend this solution to a number of folks using the Terraform provider over the past few months.

I don't know of a better solution.  Since the underlying problems seems to be with Go ignoring some system certifications, perhaps a build of Terraform-Provider-Metal with a newer Go version will overcome this.

**Comment by displague** [comment]
Version 2.0.0 and 2.0.1 of the provider are built against Go 1.16.
I wonder if we picked up a fix along the way:
* https://golang.org/doc/go1.16#crypto/tls
* https://golang.org/doc/go1.15#crypto/tls
