### ISSUE TITLE
csi-packet-controller doesn't seem to work in sites that have no EBS

### ISSUE THREAD

**Issue by claudiobartolini** [equinix/terraform-metal-multiarch-k8s#88]
See "[Elastic Block Storage is only available in Core Legacy Sites: AMS1, DFW2, EWR1, NRT1, SJC1. If you do not have access to these sites, you may reach out to our support team to request it.](https://metal.equinix.com/developers/docs/resilience-recovery/elastic-block-storage/#legacy-only-sites)"

I ran this deployment 

`auth_token = ""
  
project_id = ""

count_x86 = 3

count_arm = 0

configure_ingress = true

secrets_encryption = false

facility = "sv15"`

and my csi-packet-controller could not come up. When I ran it in 

`facility = "sjc1"`

that is one of the sites that has EBS, I didn't have this problem.
This may be obvious to more experienced engineers, but it did give me some trouble until I figured out what could be the problem (not quite sure is that, but I suspect it may be). A simple line in the readme preventing me not to deploy in sites without EBS would have helped a lot.

**Comment by jmarhee** [comment]
Sorry for the confusion. We're in the process of removing the CSI driver from this project entirely because of the availability of block storage in core sites. We're working to improve alternative storage options for the clusters this module will manage as we will be ending support for block storage in June:

https://metal.equinix.com/developers/docs/storage/elastic-block-storage/

At which time the CSI driver will no longer function.
